/**
 * Wild Workouts trainer
 * TODO
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DateHours model module.
 * @module model/DateHours
 * @version 1.0.0
 */
class DateHours {
    /**
     * Constructs a new <code>DateHours</code>.
     * @alias module:model/DateHours
     * @param hour {String} 
     * @param available {Boolean} 
     */
    constructor(hour, available) { 
        
        DateHours.initialize(this, hour, available);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, hour, available) { 
        obj['hour'] = hour;
        obj['available'] = available;
    }

    /**
     * Constructs a <code>DateHours</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DateHours} obj Optional instance to populate.
     * @return {module:model/DateHours} The populated <code>DateHours</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DateHours();

            if (data.hasOwnProperty('hour')) {
                obj['hour'] = ApiClient.convertToType(data['hour'], 'String');
            }
            if (data.hasOwnProperty('available')) {
                obj['available'] = ApiClient.convertToType(data['available'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {String} hour
 */
DateHours.prototype['hour'] = undefined;

/**
 * @member {Boolean} available
 */
DateHours.prototype['available'] = undefined;






export default DateHours;

