// Package ratings provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.8.2 DO NOT EDIT.
package ratings

import (
	"time"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
	Slug    string `json:"slug"`
}

// PostRating defines model for PostRating.
type PostRating struct {
	Comment string `json:"comment"`

	// rating score in scale from 1 to 5
	Rating int `json:"rating"`
}

// Rating defines model for Rating.
type Rating struct {
	CanRate bool       `json:"canRate"`
	Comment *string    `json:"comment,omitempty"`
	Date    *time.Time `json:"date,omitempty"`
	Rated   bool       `json:"rated"`

	// rating score in scale from 1 to 5
	Rating *int `json:"rating,omitempty"`
}

// Ratings defines model for Ratings.
type Ratings struct {
	Ratings []Rating `json:"ratings"`
}

// PostTrainingRatingJSONBody defines parameters for PostTrainingRating.
type PostTrainingRatingJSONBody PostRating

// PostTrainingRatingJSONRequestBody defines body for PostTrainingRating for application/json ContentType.
type PostTrainingRatingJSONRequestBody PostTrainingRatingJSONBody
