/**
 * Wild Workouts users
 * TODO
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UserSignIn model module.
 * @module model/UserSignIn
 * @version 1.0.0
 */
class UserSignIn {
    /**
     * Constructs a new <code>UserSignIn</code>.
     * @alias module:model/UserSignIn
     * @param login {String} 
     * @param password {String} 
     */
    constructor(login, password) { 
        
        UserSignIn.initialize(this, login, password);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, login, password) { 
        obj['login'] = login;
        obj['password'] = password;
    }

    /**
     * Constructs a <code>UserSignIn</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserSignIn} obj Optional instance to populate.
     * @return {module:model/UserSignIn} The populated <code>UserSignIn</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserSignIn();

            if (data.hasOwnProperty('login')) {
                obj['login'] = ApiClient.convertToType(data['login'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} login
 */
UserSignIn.prototype['login'] = undefined;

/**
 * @member {String} password
 */
UserSignIn.prototype['password'] = undefined;






export default UserSignIn;

