/**
 * Wild Workouts trainings
 * TODO
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TrainingTime model module.
 * @module model/TrainingTime
 * @version 1.0.0
 */
class TrainingTime {
    /**
     * Constructs a new <code>TrainingTime</code>.
     * @alias module:model/TrainingTime
     * @param time {Date} 
     */
    constructor(time) { 
        
        TrainingTime.initialize(this, time);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, time) { 
        obj['time'] = time;
    }

    /**
     * Constructs a <code>TrainingTime</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TrainingTime} obj Optional instance to populate.
     * @return {module:model/TrainingTime} The populated <code>TrainingTime</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TrainingTime();

            if (data.hasOwnProperty('time')) {
                obj['time'] = ApiClient.convertToType(data['time'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {Date} time
 */
TrainingTime.prototype['time'] = undefined;






export default TrainingTime;

