#!/usr/bin/env bash
set -euo pipefail

# Allocates a per-worktree slot so each git worktree can run its own
# docker-compose stack side by side. Every published host port is offset by
# WT_SLOT*10000; the main checkout always uses slot 0 (the default ports).
#
# Writes (both gitignored):
#   .env.worktree               port vars and host addresses derived from the slot
#   docker-compose.override.yml per-worktree compose project name (worktrees only)
#
# Idempotent: an existing .env.worktree keeps its slot unless another worktree
# claims the same one. Delete .env.worktree to force reallocation.

SPACING=10000
MAX_SLOT=5 # 5*10000 + 8788 stays below the 65535 port limit

root="$(git rev-parse --show-toplevel)"
cd "$root"

resolve() { (cd "$1" 2>/dev/null && pwd -P); }

git_dir="$(resolve "$(git rev-parse --git-dir)")"
common_dir="$(resolve "$(git rev-parse --git-common-dir)")"

slot_of() {
  [ -f "$1/.env.worktree" ] || return 0
  sed -n 's/^WT_SLOT=//p' "$1/.env.worktree" | head -n1
}

# Slots claimed by other worktrees. Slot 0 is implicitly the main checkout's.
used_slots=" 0 "
while IFS= read -r wt; do
  [ "$(resolve "$wt")" = "$(pwd -P)" ] && continue
  s="$(slot_of "$wt")"
  case "$s" in '' | *[!0-9]*) continue ;; esac
  used_slots="$used_slots$s "
done < <(git worktree list --porcelain | sed -n 's/^worktree //p')

is_used() { case "$used_slots" in *" $1 "*) return 0 ;; *) return 1 ;; esac; }

if [ "$git_dir" = "$common_dir" ]; then
  slot=0
else
  slot="$(slot_of "$root")"
  case "$slot" in '' | *[!0-9]*) slot="" ;; esac
  if [ -n "$slot" ] && { [ "$slot" -eq 0 ] || is_used "$slot"; }; then
    echo "worktree-env: slot $slot is invalid or taken by another worktree, reallocating" >&2
    slot=""
  fi
  if [ -z "$slot" ]; then
    for candidate in $(seq 1 "$MAX_SLOT"); do
      if ! is_used "$candidate"; then
        slot="$candidate"
        break
      fi
    done
  fi
  if [ -z "$slot" ]; then
    echo "worktree-env: all $MAX_SLOT slots are taken; remove an unused worktree (or its .env.worktree)" >&2
    exit 1
  fi
fi

offset=$((slot * SPACING))
port() { echo "$(($1 + offset))"; }

WEB_PORT="$(port 8080)"
TRAINER_HTTP_PORT="$(port 3000)"
TRAINER_GRPC_PORT="$(port 3010)"
TRAININGS_HTTP_PORT="$(port 3001)"
USERS_HTTP_PORT="$(port 3002)"
USERS_GRPC_PORT="$(port 3020)"
FIRESTORE_PORT="$(port 8787)"
FIRESTORE_UI_PORT="$(port 4000)"
FIRESTORE_COMPONENT_PORT="$(port 8788)"
MYSQL_PORT="$(port 3306)"

cat >.env.worktree <<EOF
# Generated by tools/worktree-env.sh — do not edit; delete to reallocate the slot.
WT_SLOT=$slot
WEB_PORT=$WEB_PORT
TRAINER_HTTP_PORT=$TRAINER_HTTP_PORT
TRAINER_GRPC_PORT=$TRAINER_GRPC_PORT
TRAININGS_HTTP_PORT=$TRAININGS_HTTP_PORT
USERS_HTTP_PORT=$USERS_HTTP_PORT
USERS_GRPC_PORT=$USERS_GRPC_PORT
FIRESTORE_PORT=$FIRESTORE_PORT
FIRESTORE_UI_PORT=$FIRESTORE_UI_PORT
FIRESTORE_COMPONENT_PORT=$FIRESTORE_COMPONENT_PORT
MYSQL_PORT=$MYSQL_PORT
CORS_ALLOWED_ORIGINS=http://localhost:$WEB_PORT
TRAINER_HTTP_ADDR=localhost:$TRAINER_HTTP_PORT
TRAINER_GRPC_ADDR=localhost:$TRAINER_GRPC_PORT
TRAININGS_HTTP_ADDR=localhost:$TRAININGS_HTTP_PORT
USERS_HTTP_ADDR=localhost:$USERS_HTTP_PORT
USERS_GRPC_ADDR=localhost:$USERS_GRPC_PORT
FIRESTORE_EMULATOR_HOST=localhost:$FIRESTORE_COMPONENT_PORT
MYSQL_ADDR=localhost:$MYSQL_PORT
EOF

override_marker="Generated by tools/worktree-env.sh"

if [ "$slot" -eq 0 ]; then
  # The main checkout uses the compose file's own project name.
  if [ -f docker-compose.override.yml ] && grep -q "$override_marker" docker-compose.override.yml; then
    rm docker-compose.override.yml
  fi
else
  branch="$(git rev-parse --abbrev-ref HEAD)"
  [ "$branch" = "HEAD" ] && branch="$(basename "$root")"
  slug="$(printf '%s' "$branch" | tr '[:upper:]' '[:lower:]' | sed -e 's/[^a-z0-9]\{1,\}/-/g' -e 's/^-*//' -e 's/-*$//')"
  [ -n "$slug" ] || slug="wt$slot"
  cat >docker-compose.override.yml <<EOF
# $override_marker — do not edit.
# Gives this worktree its own compose project so bare "docker compose"
# commands (logs, ps, exec, down) target the right stack.
name: wild-workouts-$slug
EOF
fi

echo "worktree-env: slot $slot (ports offset by $offset)" >&2
